### ISSUE TITLE
Add this project to BIDS-apps website

### ISSUE THREAD

**Issue by htwangtw** [bids-apps/giga_connectome#120]
bids-apps.github.io

**Comment by Remi-Gau** [comment]
this should be done: note though there are 2 dashboards from that repo that should show slightly different info (ideally).

- The dashboard in the readme is mostly for developpers and bids maintainers and should show the test status of the main branch

https://github.com/bids-apps/bids-apps.github.io?tab=readme-ov-file#dashboard

- the dashboard in the website is for bids app users and SHOULD show the status of tests run on the latest stable docker image (if this is red, users should be very careful on using the app)

https://bids-apps.neuroimaging.io/apps/

Ideally we want to have this for all apps, which means having a CI workflow that tests the main branch (which giga_connectome has) and one that tests the latest stable docker image (which giga_connectome does not have).

I will work on this and will likely have to tackle the following issues at the same time:
- #69 
- #75 
- #119
