### ISSUE TITLE
[BUG] the file names in working directory is not a template, it should be sub-xxx

### ISSUE THREAD

**Issue by htwangtw** [bids-apps/giga_connectome#143]
### What version of the bids app were you using?

0.5.0

### Describe your problem in detail.

They are not templates so it should be the subject specificity labels from fmriprep.

### What command did you run?

N/A

### Describe what you expected.

For example:
In this [artefact](https://github.com/bids-apps/giga_connectome/actions/runs/8922234067/artifacts/1466700921)
`/working_dir/groupmasks/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_atlas-DiFuMo_res-dataset_desc-64dimensions_probseg.nii.gz`

should be

`/working_dir/groupmasks/sub-1/sub-1_seg-DiFuMo_desc-64dimensions_probseg.nii.gz`

For the time series / connectome data,

`sub-1_ses-timepoint1_task-probabilisticclassification_run-01_space-MNI152NLin2009cAsym_res-2_atlas-Schaefer20187Networks_desc-200Parcels7NetworksSimple_timeseries.tsv`

it should be
`sub-1_ses-timepoint1_task-probabilisticclassification_run-01_seg-Schaefer20187Networks200Parcels_desc-denoiseSimple_timeseries.tsv`

@effigies @oesteban @tsalo
Would this change be correct?

**Comment by tsalo** [comment]
I like the atlas+desc --> seg change, but I think it makes sense to include space and resolution in the files still, since that will affect the parcellation.

**Comment by htwangtw** [comment]
Space and resolution will be the meta data associated with the `seg` entity if I understand @effigies's suggestion correctly.
So the working directory is actually something important to organise into `atlases/` mentioned in BEP17.
 
I have created a mocked layout: 
```
atlases/
└── sub-1/func/
            ├── sub-1_seg-Schaefer20187Networks100Parcels_dseg.nii.gz
            ├── sub-1_seg-Schaefer20187Networks100Parcels_dseg.json
            ├── sub-1_space-MNI152NLin2009cAsym_res-2_label-GM_mask.nii.gz
            └── sub-1_space-MNI152NLin2009cAsym_res-2_label-GM_mask.json
```

`sub-1_seg-Schaefer20187Networks100Parcels_dseg.json`:
```json
{
    "BIDSVersion": "1.9.0.dev",
    "SpatialReference": "sub-1_space-MNI152NLin2009cAsym_res-2_label-GM_mask.nii.gz",
    "Space": "MNI152NLin2009cAsym",
    "Resolution": "Matched with original resolution in subject EPI scan space (2x2x2 mm^3)",
    "Sources": []
}
```

`sub-1_space-MNI152NLin2009cAsym_res-2_label-GM_mask.json`:
```json
{
    "BIDSVersion": "1.9.0.dev",
    "SpatialReference": "sub-1_space-MNI152NLin2009cAsym_res-2_label-GM_mask.nii.gz",
    "Space": "MNI152NLin2009cAsym",
    "Resolution": "Matched with original resolution in subject EPI scan space (2x2x2 mm^3)",
    "Sources": [<list of the brain mask files of sub-1>, <templateflow tpl-MNI152NLin2009cAsym GM file>]
}
```

`connectome_output/sub-1/ses-timepoint1/func/`:
```
├── sub-1_ses-timepoint1_task-probabilisticclassification_run-01_desc-denoiseSimple_timeseries.json
├── sub-1_ses-timepoint1_task-probabilisticclassification_run-01_seg-Schaefer20187Networks100Parcels_desc-denoiseSimple_timeseries.tsv
├── sub-1_ses-timepoint1_task-probabilisticclassification_run-01_seg-Schaefer20187Networks100Parcels_meas-PearsonCorrelation_desc-denoiseSimple_relmat.tsv
├── sub-1_ses-timepoint1_task-selectivestopsignaltask_run-01_desc-denoiseSimple_timeseries.json
├── sub-1_ses-timepoint1_task-selectivestopsignaltask_run-01_seg-Schaefer20187Networks100Parcels_desc-denoiseSimple_timeseries.tsv
└── sub-1_ses-timepoint1_task-selectivestopsignaltask_run-01_seg-Schaefer20187Networks100Parcels_meas-PearsonCorrelation_desc-denoiseSimple_relmat.tsv
```
