### ISSUE TITLE
Add the number of confound regressors used to the BIDS metadata

### ISSUE THREAD

**Issue by HippocampusGirl** [bids-apps/giga_connectome#144]
### Your idea

To evaluate the impact of different denoising strategies, it may be useful to know how many temporal degrees of freedom were lost. This could be, for example
```json
{
    "ConfoundRegressors": ["a_comp_cor_98"],
    "NumberOfVolumesDiscardedByMotionScrubbing": 5,
    "NumberOfVolumesDiscardedByNonsteadyStatesDetector": 5,
    "SamplingFrequency": 0.5
}
```

**Comment by htwangtw** [comment]
Mean frame wise displacement should also there too
