### ISSUE TITLE
Migrate to `bids-apps/rs_signal_extract`

### ISSUE THREAD

**Issue by htwangtw** [bids-apps/giga_connectome#5]
https://github.com/bids-apps/rs_signal_extract/

It's already written as a BIDS-app, might as well.

**Comment by Remi-Gau** [comment]
one possibility for this if you do not want to keep the same name

- move https://github.com/SIMEXP/giga_connectome to the bids-app organization
- flag https://github.com/bids-apps/rs_signal_extract/ as unmaintained / deprecated / superseeded by giga_connectome

**Comment by htwangtw** [comment]
That also sounds easier
I don't have any attunement to the name.... let me think about it

**Comment by htwangtw** [comment]
DONE
