### ISSUE TITLE
Add explicit test for dataset without session level

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/giga_connectome#89]
Mostly as a sanity check as I have seen a lot of bids apps struggling to handle both of those cases. 

Should be possible to use nilearn internals to mock fmriprep datasets as the test dataset only cover one of those.

**Comment by htwangtw** [comment]
Right now the test dataset has session but internally we have run several datasets without the session level at this point and the problem is solved. We can add an explicit test for this later.

**Comment by Remi-Gau** [comment]
okidoki!!
